/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qos' at '11/25/15 2:21 PM' with Gradle 2.9
 *
 * @author qos, @date 11/25/15 2:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
